### ISSUE TITLE
Fix the comment system

### ISSUE THREAD

**Issue by Commenter123** [owncloud/appstore-issues#37] opened 2015-12-02 11:05 UTC
The current comment system at apps.owncloud.com really discourages people to download any app.

You can't delete nor edit a comment, and it happens so often that users of my app accidentally double-post a comment. This is due to the bad comment system.

It would also make sense to let app developers delete comments and whole comment threads.

I personally would not want to download an app whose comment section is so cluttered with bad comments, double-comments, incorrect comments, responses to comments not at a comment's thread level, but as a complete new comment, ..

Please fix this. It will make the apps.owncloud.com site usable, which it currently definitely isn't :(

**Comment by ghost** [comment] 2016-07-30 07:59
Partly a duplicate of https://github.com/owncloud/appstore-issues/issues/17

Overall i think the whole comment system as well as the knowledge base (https://github.com/owncloud/appstore-issues/issues/23) should be disabled completely.

Reason:

Both are mostly misused as bugtracker and the apps.owncloud.com page is also just another additional communication channel (additionally to mailinglist and central).

**Comment by DeepDiver1975** [comment] 2017-07-13 12:14
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/

**Closed as completed by DeepDiver1975** 2017-07-13 12:14 UTC
