### ISSUE TITLE
App store not returning updates

### ISSUE THREAD

**Issue by PVince81** [owncloud/appstore-issues#3] opened 2014-07-24 09:58 UTC
From OC 6.0.4 I don't get any upgrades.

```
$ curl 'http://apps.owncloud.com/updater.php?version=6x0x4x1x1406140131.3933x1406140652xstablexx2014-06-24T15:11:49+00:00'

<?xml version="1.0"?>
<owncloud>
  <version></version>
  <versionstring></versionstring>
  <url></url>
  <web></web>
</owncloud>
```

Or are only minor upgrades supported there ?

**Comment by PVince81** [comment] 2014-07-24 09:58
@karlitschek @VicDeo

**Comment by VicDeo** [comment] 2014-07-28 14:01
Feed will be updated with  7.0.1 release

**Comment by MorrisJobke** [comment] 2014-07-28 14:56
same on ownCloud 7 instance

**Comment by VicDeo** [comment] 2014-07-30 14:39
Duplicate of https://github.com/owncloud/updater/issues/21

> Feed will be updated with 7.0.1 release

This is done intentionally. Closing

**Closed as completed by VicDeo** 2014-07-30 14:39 UTC
Labels: bug
